=== OpenHCOS/radio-to-broadcast/rtob-common/raw/service-codes-180420.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Service",
  "description": "A Service Code List",
  "type": "object",
  "definitions": {
    "Service": {
      "type": "object",
      "properties": {
        "serviceType": { "type": "string" },
        "price": { "type": "number" },
        "priceRemote": { "type": "number" }
      },
      "additionalProperties": false
    },
    "ServiceMap": {
      "type": "object",
      "patternProperties": {
        "^[A-Z]+": {"$ref": "#/definitions/Service" }
      },
      "additionalProperties": false
    },
    "JsonLdContext": {
      "description": "A link to a valid JSON-LD context file",
      "oneOf": [
        { "type": "string" },
        { "type": "object" },
        {
          "type": "array",
          "items": { "type": "string" }
        }
      ]
    }
  },
  "properties": {
    "@context": { "$ref": "#/definitions/JsonLdContext" },
    "@schema":{ "type": "string" , "format": "uri"},
    "@id": {
      "description": "The unique identifier for a service list",
      "type": "string"
    },
    "serviceMap": { "$ref": "#/definitions/ServiceMap" }
  },
  "required": ["@id", "@schema", "serviceMap"],
  "additionalProperties": true
}

=== OpenHCOS/radio-to-broadcast/docs/json/service-codes-180420.json
{
    "@context": "https://openhcos.github.io/radio-to-broadcast/schema/service-codes-180420.ld.json",
    "@schema": "https://openhcos.github.io/radio-to-broadcast/schema/service-codes-180420.schema.json",
    "@id": "https://https://openhcos.github.io/radio-to-broadcast/service-codes-181420",
    "serviceMap": {
        "AA01": {
            "serviceType": "照顧計畫擬定與服務連結",
            "price": 1500,
            "priceRemote": 1800
        },
        "AA02": {
            "serviceType": "照顧管理",
            "price": 300,
            "priceRemote": 360
        },
        "AA03": {
            "serviceType": "照顧服務員配合專業服務",
            "price": 600,
            "priceRemote": 720
        },
        "AA04": {
            "serviceType": "於臨終日提供服務加計",
            "price": 1200,
            "priceRemote": 1440
        },
        "AA05": {
            "serviceType": "照顧困難之服務加計",
            "price": 100,
            "priceRemote": 120
        },
        "AA06": {
            "serviceType": "身體照顧困難加計",
            "price": 200,
            "priceRemote": 240
        },
        "AA07": {
            "serviceType": "家庭照顧功能微弱之服務加計",
            "price": 760,
            "priceRemote": 915
        },
        "AA08": {
            "serviceType": "晚間服務",
            "price": 385,
            "priceRemote": 465
        },
        "AA09": {
            "serviceType": "例假日服務",
            "price": 770,
            "priceRemote": 925
        },
        "AA10": {
            "serviceType": "夜間緊急服務",
            "price": 1000,
            "priceRemote": 1200
        },
        "BA01": {
            "serviceType": "基本身體清潔",
            "price": 260,
            "priceRemote": 310
        },
        "BA02": {
            "serviceType": "基本日常照顧",
            "price": 310,
            "priceRemote": 370
        },
        "BA03": {
            "serviceType": "測量生命徵象",
            "price": 35,
            "priceRemote": 40
        },
        "BA04": {
            "serviceType": "協助餵食或灌食",
            "price": 130,
            "priceRemote": 155
        },
        "BA05": {
            "serviceType": "餐食照顧",
            "price": 310,
            "priceRemote": 370
        },
        "BA06": {
            "serviceType": "協助沐浴",
            "price": 290,
            "priceRemote": 350
        },
        "BA07": {
            "serviceType": "協助沐浴及洗頭",
            "price": 325,
            "priceRemote": 385
        },
        "BA08": {
            "serviceType": "足部照護",
            "price": 500,
            "priceRemote": 600
        },
        "BA09": {
            "serviceType": "到宅沐浴車服務",
            "price": 1500,
            "priceRemote": 1800
        },
        "BA10": {
            "serviceType": "翻身拍背",
            "price": 155,
            "priceRemote": 190
        },
        "BA11": {
            "serviceType": "肢體關節活動",
            "price": 195,
            "priceRemote": 235
        },
        "BA12": {
            "serviceType": "協助上(下)樓梯",
            "price": 130,
            "priceRemote": 155
        },
        "BA13": {
            "serviceType": "陪同外出",
            "price": 195,
            "priceRemote": 235
        },
        "BA14": {
            "serviceType": "陪同就醫",
            "price": 685,
            "priceRemote": 825
        },
        "BA15": {
            "serviceType": "家務協助",
            "price": 195,
            "priceRemote": 235
        },
        "BA16": {
            "serviceType": "代購或代領或代送服務",
            "price": 130,
            "priceRemote": 155
        },
        "BA17": {
            "serviceType": "協助執行輔助性醫療",
            "price": 65,
            "priceRemote": 80
        },
        "BA18": {
            "serviceType": "安全看視",
            "price": 400,
            "priceRemote": 480
        },
        "BA19": {
            "serviceType": "安全看視（續）",
            "price": 200,
            "priceRemote": 240
        },
        "BA20": {
            "serviceType": "陪伴服務",
            "price": 350,
            "priceRemote": 420
        },
        "BA21": {
            "serviceType": "陪伴服務（續）",
            "price": 175,
            "priceRemote": 210
        },
        "BA22": {
            "serviceType": "巡視服務",
            "price": 130,
            "priceRemote": 160
        },
        "BB01": {
            "serviceType": "日間照顧（全日）--第1型",
            "price": 675,
            "priceRemote": 810
        },
        "BB02": {
            "serviceType": "日間照顧（半日）--第1型",
            "price": 340,
            "priceRemote": 405
        },
        "BB03": {
            "serviceType": "日間照顧（全日）--第2型",
            "price": 840,
            "priceRemote": 1005
        },
        "BB04": {
            "serviceType": "日間照顧（半日）--第2型",
            "price": 420,
            "priceRemote": 505
        },
        "BB05": {
            "serviceType": "日間照顧（全日）--第3型",
            "price": 920,
            "priceRemote": 1105
        },
        "BB06": {
            "serviceType": "日間照顧（半日）--第3型",
            "price": 460,
            "priceRemote": 555
        },
        "BB07": {
            "serviceType": "日間照顧（全日）--第4型",
            "price": 1045,
            "priceRemote": 1255
        },
        "BB08": {
            "serviceType": "日間照顧（半日）--第4型",
            "price": 525,
            "priceRemote": 630
        },
        "BB09": {
            "serviceType": "日間照顧（全日）--第5型",
            "price": 1130,
            "priceRemote": 1355
        },
        "BB10": {
            "serviceType": "日間照顧（半日）--第5型",
            "price": 565,
            "priceRemote": 680
        },
        "BB11": {
            "serviceType": "日間照顧（全日）--第6型",
            "price": 1210,
            "priceRemote": 1450
        },
        "BB12": {
            "serviceType": "日間照顧（半日）--第6型",
            "price": 605,
            "priceRemote": 725
        },
        "BB13": {
            "serviceType": "日間照顧（全日）--第7型",
            "price": 1285,
            "priceRemote": 1540
        },
        "BB14": {
            "serviceType": "日間照顧（半日）--第7型",
            "price": 645,
            "priceRemote": 770
        },
        "BC01": {
            "serviceType": "家庭托顧（全日）--第1型",
            "price": 625,
            "priceRemote": 750
        },
        "BC02": {
            "serviceType": "家庭托顧（半日）--第1型",
            "price": 315,
            "priceRemote": 375
        },
        "BC03": {
            "serviceType": "家庭托顧（全日）--第2型",
            "price": 760,
            "priceRemote": 915
        },
        "BC04": {
            "serviceType": "家庭托顧（半日）--第2型",
            "price": 380,
            "priceRemote": 460
        },
        "BC05": {
            "serviceType": "家庭托顧（全日）--第3型",
            "price": 785,
            "priceRemote": 945
        },
        "BC06": {
            "serviceType": "家庭托顧（半日）--第3型",
            "price": 395,
            "priceRemote": 475
        },
        "BC07": {
            "serviceType": "家庭托顧（全日）--第4型",
            "price": 880,
            "priceRemote": 1055
        },
        "BC08": {
            "serviceType": "家庭托顧（半日）--第4型",
            "price": 440,
            "priceRemote": 530
        },
        "BC09": {
            "serviceType": "家庭托顧（全日）--第5型",
            "price": 960,
            "priceRemote": 1155
        },
        "BC10": {
            "serviceType": "家庭托顧（半日）--第5型",
            "price": 480,
            "priceRemote": 580
        },
        "BC11": {
            "serviceType": "家庭托顧（全日）--第6型",
            "price": 980,
            "priceRemote": 1180
        },
        "BC12": {
            "serviceType": "家庭托顧（半日）--第6型",
            "price": 490,
            "priceRemote": 590
        },
        "BC13": {
            "serviceType": "家庭托顧（全日）--第7型",
            "price": 1040,
            "priceRemote": 1250
        },
        "BC14": {
            "serviceType": "家庭托顧（半日）--第7型",
            "price": 520,
            "priceRemote": 625
        },
        "BD01": {
            "serviceType": "社區式協助沐浴",
            "price": 200,
            "priceRemote": 240
        },
        "BD02": {
            "serviceType": "社區式晚餐",
            "price": 150,
            "priceRemote": 180
        },
        "BD03": {
            "serviceType": "社區式服務交通接送",
            "price": 35,
            "priceRemote": 45
        },
        "CA01": {
            "serviceType": "IADLs復能照護--居家",
            "price": 4500,
            "priceRemote": 5400
        },
        "CA02": {
            "serviceType": "IADLs復能照護--社區",
            "price": 4050,
            "priceRemote": 4860
        },
        "CA03": {
            "serviceType": "ADLs復能照護--居家",
            "price": 4500,
            "priceRemote": 5400
        },
        "CA04": {
            "serviceType": "ADLs復能照護--社區",
            "price": 4050,
            "priceRemote": 4860
        },
        "CA05": {
            "serviceType": "社區適應--居家",
            "price": 6000,
            "priceRemote": 7200
        },
        "CA06": {
            "serviceType": "社區適應--社區",
            "price": 5400,
            "priceRemote": 6480
        },
        "CB01": {
            "serviceType": "營養照護",
            "price": 4000,
            "priceRemote": 4800
        },
        "CB02": {
            "serviceType": "進食與吞嚥照護",
            "price": 9000,
            "priceRemote": 10800
        },
        "CB03": {
            "serviceType": "困擾行為照護",
            "price": 4500,
            "priceRemote": 5400
        },
        "CB04": {
            "serviceType": "臥床或長期活動受限照護",
            "price": 9000,
            "priceRemote": 10800
        },
        "CC01": {
            "serviceType": "居家環境安全或無障礙空間規劃",
            "price": 2000,
            "priceRemote": 2400
        },
        "CD01": {
            "serviceType": "居家護理訪視",
            "price": 1300,
            "priceRemote": 1300
        },
        "DA01": {
            "serviceType": "交通接送",
            "price": 0,
            "priceRemote": 0
        },
        "GA01": {
